language: cpp
sudo: false
dist: trusty

addons:
  apt:
    packages: &common_deps
      - ninja-build

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_deps
            - g++-6


    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - *common_deps
            - clang-4.0

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -G Ninja ..
  - cmake --build . --target all

