language: cpp
sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages: &common_deps
      - ninja-build
      - cmake
      - g++-6
      - clang-4.0

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - ninja

